name = "thebullandbloom"
main = "src/index.ts"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./site"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "none"

[[d1_databases]]
binding = "DB"
database_name = "bullandbloom"
database_id = "48c896fa-161a-4bca-9a0b-4a111c91c354"
migrations_dir = "migrations"

[triggers]
crons = ["*/15 * * * *"]

[vars]
SITE_URL = "https://thebullandbloom.com"
